---
- hosts: all
  vars:
      list_of_ssh_ports: [2122, 22]
  tasks:
    - name: copy file to remote host
      synchronize: src=/tmp/stam.txt dest=/tmp/stam.txt dest_port=2122
      delegate_to: 192.168.1.5
